### ISSUE TITLE
Multiple ensembles in one file

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/qp#103]
It would be handy to have a straightforward way to save a collection of ensembles to a single file, to represent different tomographic bins. The easiest way to do this would just be to let us specify an HDF group to save to instead of just a filename.  If there's already a way that I've just missed then let me know.

**Comment by eacharles** [comment]
I need to think about this, and how we would do it for other persistent formats, or if this is an HDF5 only feature.

**Comment by eacharles** [comment]
Does  just using the ancillary data to categories  for PDFs work?   Or do we really need to be able to write to multiple groups in an HDF5 files?

**Comment by aimalz** [comment]
As per today's discussion, this will be dealt with as bin IDs as `ancil` data instead of multiple ensembles in one file.
