### ISSUE TITLE
qp not compatible with scipy 1.9.0

### ISSUE THREAD

**Issue by jeremykubica** [LSSTDESC/qp#105]
Version 1.9.0 of scipy introduced a change ([PR here](https://github.com/scipy/scipy/pull/15794), [diff here](https://github.com/scipy/scipy/commit/70a76cbcea11d959bcfdf7ee9df983bfac30e170)) that removed removed the pdf function from `rv_frozen` and instead implements it in `rv_continuous_frozen`. Since `rv_frozen_func` inherits from `rv_frozen`, qp now produces the following error in tests/test_metrics.py:

AttributeError: 'rv_frozen_func' object has no attribute 'pdf'

**Comment by aimalz** [comment]
Thank you very much @jeremykubica and @maxwest-uw for identifying this problem! I think the easiest temporary fix is to specify a version in the `setup.py` but please do feel free to implement whatever solution you deem best.

**Comment by jeremykubica** [comment]
I put together a PR (#107) to solve this, but scipy 1.9.0 doesn't seem compatible with the python 3.7 test. Any suggestions are welcome.

**Comment by sschmidt23** [comment]
RAIL, the main (but not the only) consumer of qp, already has `python_requires=">=3.8"` due to some issues with earlier scipy and numpy versions, so maybe it is time to also eliminate python 3.7 from the qp tests.  Thoughts?

**Comment by eacharles** [comment]
Yes, let's chuck out 3.7

**Comment by eacharles** [comment]
Fixed with #108
