### ISSUE TITLE
Parallel write tests not working

### ISSUE THREAD

**Issue by jeremykubica** [LSSTDESC/qp#106]
After doing a clean install on a Mac laptop, the parallel write tests in test_ensembles.py fails with the message:

`TypeError: hdf5py module not prepared for parallel writing.`

**Comment by maxwest-uw** [comment]
I was able to get all the tests working on my local machine with
`conda install -c conda-forge "h5py>=2.9=mpi*" `
although we should probably make sure to either add this to the setup instructions or change setup.py/requirements.txt :)

**Comment by eacharles** [comment]
Ok, my take on this is that `qp` shouldn't need the parallel version of hdf5.  So I just put in a pytest.skip if that version isn't present (i.e., when you are testing locally).

**Comment by eacharles** [comment]
Done in #108
