### ISSUE TITLE
Normalization guarantees

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#12]
A way to force normalization has come up both in the context of a qp-based reimplementation of [chippr](github.com/aimalz/chippr) that's relevant to #10 and the implementation of existing and planned qp parameterizations, e.g. splines and the FlexCode parameterization, respectively. To avoid unnecessary conversions, maybe it could be one of the `._*()` methods of `Pdf_rows_gen`?

**Comment by eacharles** [comment]
So, the normalization is forced by default, that is pretty much a  requirement of scipy.stats.  There is an option to skip forcing the normalizaiton on construction for speed.

**Comment by aimalz** [comment]
I'm not sure I understand how this can be guaranteed for the spline parameterization in particular, and I think it will matter for the FlexCode Fourier basis parameterization. Don't we have to specify a range over which the PDF integrates to 1? Is the enforcement done by evaluating the PDF on a grid, and, if so, how is it specified? And where are we specifying how to handle negative values? So sorry if I'm missing something obvious here -- apparently I've been wondering about this since January and wasn't paying attention when the answer was implemented.

**Comment by eacharles** [comment]
qp.spline_gen() assumes the spline are normalized arlready

qp.spline_gen.create_from_samples() and qp.spline_gen.create_from_xy_vals() will normalize the spline for you.  In the first case the integration range for the normalization is defined between the lowest and highest samples, in the second case it is defined by the x-values.   It would be easy to let the integration range be passed as a kwarg.

-e
