### ISSUE TITLE
Packed integer representation

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/qp#126]
Depending on how #130 is done, this ticket might be taken care of automatically.

**Comment by drewoldag** [comment]
We should ask Eric if there's already some documentation to help out with the engineering.

**Comment by eacharles** [comment]
So, what I had in mind here was something like using an interpolation on a fixed grid, but storing 8-bit unsigned integers instead of floats at each grid point.
We could, by way of example, cast the highest value of the pdf to be 255, or we could have the total sum to 255.

**Comment by aimalz** [comment]
I have an implementation question that's outside the scope of the PR but still relevant to this issue. Why not have the packed integer option available for all parameterizations rather than being specific to interpolation on a grid? Can't the parameters associated with any parameterization be saved in this way?

**Comment by eacharles** [comment]
Yes, but because of the way that qp is set up to persist data it isn’t really an option that you turn on or off for a particular representation, but rather it’s way down there in the guts what it means to have a representation.Also, packing schemes depend on the details of what you are packing, so the actual packing scheme would probably be different for each representation.   E.g.,  how do you pack the mix-mix parameters into 8bit integers.  It’s gonna be different for means, weights, and widths.We could try to come up with a generic packing layer, but it would be a fair bit pretty tricky work.  And it would be a bit redundant since e.g., FITS already has stuff that look like packing schemes.On Mar 10, 2023, at 7:02 AM, Alex Malz ***@***.***> wrote:﻿
I have an implementation question that's outside the scope of the PR but still relevant to this issue. Why not have the packed integer option available for all parameterizations rather than being specific to interpolation on a grid? Can't the parameters associated with any parameterization be saved in this way?
