### ISSUE TITLE
adding sparse function representation for mixture of model

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/qp#13]
This aims to bring to qp the work done in https://pythonhosted.org/MLZ/sparse.html using Voigt profiles. Earlier studies showed remarkable ability to capture almost completely any random pdf sampled from DC1 PZ effort.

**Comment by johannct** [comment]
looks like I am not authorized to assign this to myself

**Comment by aimalz** [comment]
I believe this was completed a long time ago. Should we close the issue or keep it open as an umbrella for a generalized mixture model parameterization?
