### ISSUE TITLE
FlexZBoost storage parameterization

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#130]
This was previously not considered because of the computational overhead of going from this native parameterization to evaluation on a grid, but for commissioning, storage is a bigger issue because the reconstruction process won't be done on all galaxies all at once.

**Comment by drewoldag** [comment]
- [ ] Create the flexzboost_gen class
- [ ] Demo notebook
- [ ] Add tests
- [ ] Documentation

**Comment by drewoldag** [comment]
Note for Drew later, if using `basis_coefs` as the data object in the Ensemble, will we be able to combine Ensembles easily? 

Need to investigate the way that RAIL batches together chunks of Ensembles.

**Comment by drewoldag** [comment]
The answer to the question in the last comment was "yes"
