### ISSUE TITLE
Abstract away IO within qp

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/qp#15]
Eventually qp may just be requested to hand over its product to an external DESC code in charge of centralizing IO and file persistence, metadata, provenance etc.... For the time being, define the qp api and move the relevant IO/persistence code to a separate qp module so that it can be extracted later on

**Comment by eacharles** [comment]
Hi Johann.  
In practice, this is already done   We are using astropy.table.write to write the files.   Depending on the filename it writes the corresponding file type.     
If people want to re-visit this once they have a proposal for specific file types I think what would be fine.  But for now I suspect that this is as good a solution as anything out there.

**Comment by johannct** [comment]
Precisely, we are brainstorming about rationalizing "what is out there". In the long run, it is very unlikely that we let qp do its own file saving, while other codes not depending on qp would necessarily have another scheme. And we need to rationalize and centralize these schemes because we need to be sure that we are consistent in naming, access, metadata, provenance, etc.... So for the time being we are perhaps ok to continue developing rail, but I bet not in the long run.

**Comment by eacharles** [comment]
Well, note that qp already provide a method to access formatted data that would get written to a file with Ensemble.build_tables(), which returns a dictionary of astropy.Table objects, which can easily be turned into panda dataframes or dictionaries of numpy arrays.   

The whole of the writing 'specialization' is this:

```
        basename, ext = os.path.splitext(filename)
        meta_ext = "_meta%s" % ext
        meta_filename = basename + meta_ext

        tables = self.build_tables()
        tables['meta'].write(meta_filename, overwrite=True)
        tables['data'].write(filename, overwrite=True)

```

So I think that all you really need is some generic function to write a dictionary of astropy tables into whatever file format you want.

**Comment by eacharles** [comment]
On the reading side, the specialization comes down to this code in `qp.Factory.read(filename)`
```

        basename, ext = os.path.splitext(filename)
        meta_ext = "_meta%s" % ext
        meta_filename = basename + meta_ext

        md_table = Table.read(meta_filename)
        data_table = Table.read(filename)

        data = self._build_data_dict(md_table, data_table)

```

Once the data object is built, it can be used to create an Ensemble.

**Comment by eacharles** [comment]
mergin into: https://github.com/LSSTDESC/qp/issues/45

**Comment by eacharles** [comment]
Moved functions to io_layer.py in #45
