### ISSUE TITLE
Create `.../tests/distribution_generator_tests/` subdirectory. Break apart `test_ensemble.py` and move the `quant_gen` specific tests into their own unittest module - `test_quant_gen.py`.

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/qp#153]
Create `.../tests/distribution_generator_tests/` subdirectory. Break apart `test_ensemble.py` and move the `quant_gen` specific tests into their own unittest module - `test_quant_gen.py`. 

Ideally create stub (or more than stub) test files for the various `*_gen` modules.

**Comment by eacharles** [comment]
Sorry, could you clarify why you want to do this?
