### ISSUE TITLE
Generalize packed integer option to all parameterizations

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#161]
This issue is for at least investigating and, if feasible, implementing a generic way to save any ensemble as packed integers rather than floats (or as lower-bit floats), extending the work done for the `interp` parameterization in #126 to any qp parameterization.

**Comment by eacharles** [comment]
There really isn't a great way of doing this in the current implementation.   We can do this on a case-by-case bases as needed.

**Comment by aimalz** [comment]
@eacharles Based on discussions with @drewoldag, there might be a more general way to do it at the level of file i/o that would retain the benefits of the storage footprint even if maintaining the smaller size when ensembles are instantiated in memory might not be feasible without the more involved process you executed for the interp parameterization. I labeled the issue as enhancement since the generalization isn't a top priority right now, but it's a nice idea worth keeping in the back of our minds in case a path forward arises.

**Comment by aimalz** [comment]
This is looking infeasible at the moment so I'm closing the issue.
