### ISSUE TITLE
Python project template for automation/smoke tests

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#182]
[link for reference](https://github.com/lincc-frameworks/python-project-template) All the cool kids, by which I mean many of the RAILiverse packages, seem to be doing it so we might want to consider it here as well, particularly for synching the GA and various automation rules (e.g. adding new issues to [the GH Project ](https://github.com/orgs/LSSTDESC/projects/6)) to behave the same way as in the other repos. _EDIT: Whoops, I was on autopilot and referenced the RAIL-specific one. I think we can get the stuff we want from it without switching to the template though._

EDIT: Also, #191 could have been avoided by the quick example code being embedded from a standalone script or notebook and being run as part of regular smoke tests, which might be easier to set up through the template than on their own.

**Comment by eacharles** [comment]
done with #197
