### ISSUE TITLE
qp file I/O for iterating chunks of data rather than a single large dataset

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#24]
Given the sometimes very large file sizes (e.g. tracts and healpix pixels on the backend of gcr-catalogs contain several million galaxies per file, and I believe TXPipe creates one giant file with the entire cosmology sample), we currently have the ability in RAIL/estimation to break the input data into smaller chunks that are fed to the PZ code (which will also be useful for parallelization).  In switching the output format to qp, we then need to join these chunks back into the original single data set (in a way that preserves ordering if we are going to continue to make joined catalogs in gcr-catalogs, which uses exact line ordering to save time in several instances).  
As mentioned in a separate discussion, this aggregation could be accomplished by either one of supplying a method to append data to an existing qp ensemble (after a check that the parameterization is the same), or developing a container class that treats a collection of chunks in the same manner as a single large file.

**Comment by sschmidt23** [comment]
While working on a demo notebook for RAIL/estimation, I wrote a quick and dirty "append" method for qp data, a more optimized version of something like this function would be very useful for aggregating qp data as we iterate through a file.  I do think something like this should be native to qp, rather than living in RAIL.

```
def qpappend(ens1,ens2):
    n1meta = ens1.metadata()
    n2meta = ens1.metadata()
    for key in n1meta.keys():
        if isinstance(n1meta[key], np.ndarray):
            if n1meta[key].any() != n2meta[key].any():
                print("parameterizations differ!")
                exit(2)
        else:
            if n1meta[key] != n2meta[key]:
                print("parameterizations differ!")
                exit(2)
    n1data = ens1.objdata()
    n2data = ens2.objdata()
    for key in n1data.keys():
        n1data[key] = np.vstack([n1data[key], n2data[key]])
    ens1.update_objdata(n1data)
    return ens1
```

**Comment by eacharles** [comment]
Merging this into https://github.com/LSSTDESC/qp/issues/45
