### ISSUE TITLE
Modifications for interoperability with GCRCatalogs

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#36]
I'm going to attempt a quick and dirty demo notebook on using the data from GCRCatalogs/flat files of CosmoDC2_v1.1.4/run2.2i with qp.  This is likely going to need a few extra options, e.g. appending qp datasets together, maybe an alternative write-out format to parquet, etc...

I'm creating this issue as a catch-all for those extras, and will put anything I come up with in a branch associated with this issue.

**Comment by eacharles** [comment]
https://github.com/LSSTDESC/qp/pull/39
