### ISSUE TITLE
Slow moment calculations for interp_pdf ensembles

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#40]
The default integrate.quad performed by the scipy stats/moments calculation is extremely slow for the interp parameterization, both for momtype=0 (integrate PDF over support) or momtype=1 (integrate PPF from 0 to 1).  For example, a sample set of 200 PDFs from a flexzboost distribution takes ~7 mins 30secs to compute the first four moments with `stats('mask')`, and well over a minute for just the means..  We should write a custom integration/non-central moment calculation for this particular subclass to speed this up.

**Comment by sschmidt23** [comment]
I wrote a subclass-specific `_munp` function and used the discrete-style calculation of moments that should work just for this particular subclass because we have things on a regular grid, it appears to be ~200,000x faster, taking 2.2ms rather than 7min30s to compute the stats for my example data and some test Gaussians sampled on a grid.

Note: while mean and variance calculations appear to be exactly correct, the values of Skew and Kurtosis seem to be off for a set of demo Gaussians, likely due to numerical effects; however, looking at the integrate.quad values for skew and kurtosis, they seem to be even further off from the true values.  So, no actual current functionality is being lost here.

**Comment by eacharles** [comment]
Merged in  #42
