### ISSUE TITLE
Fix padding for quant pdf.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/qp#46]
Fix the `pad_quantiles` function to be smarter about extrapolating outside the range provided.

**Comment by eacharles** [comment]
merged in #48

**Comment by aimalz** [comment]
The padding for quantiles saves the padded values, bloating the size of the saved file. Also, setting `check_input=False` upon instantiation does not prevent padding the quantiles.

**Comment by drewoldag** [comment]
Related to #8

**Comment by drewoldag** [comment]
WRT to the second part of @aimalz April 21, 2022 comment - setting `check_input=False` is now being respected after this PR: https://github.com/LSSTDESC/qp/pull/152

**Comment by drewoldag** [comment]
Closing this issue after PR #152 which will now respect the `check_input=False` input.
