### ISSUE TITLE
Multimodal PDFs in the interpolated quantile parameterization

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#65]
As discussed a bit in the #desc-pz-rail slack channel today (Oct 5th), the CDF derivative form in the updated quantile parameterization works very well in most cases, however, when you have multimodal PDFs you can imprint a false peak in between sharp peaks due to the empirical derivative values calculated from the CDF.  An example of such a situation is included as a figure for illustration, a "real" PDF output from BPZ stored with 51 quantiles
![xtestfig51](https://user-images.githubusercontent.com/11219330/136102913-bf158f7f-aaef-4425-8ead-ea06b7a38cdf.jpg)
.

**Comment by drewoldag** [comment]
I did a bunch of investigations around this, and it seems like the behavior here is not a result of any inherently bad code per se, but a result of under sampling the CDF when generating the (quantile,CDF) pairs. 

In PR #134 I have included a `nb/quantile_parameterization_difficult_examples.ipynb` (based on one created by @sschmidt23) to show how a different sampling of the quantiles can lead to a much better representation of the original PDF. The code is likely naive, and I make no claims that what is in the notebook is ready for production. 

The results seem on par with the piecewise constant implementation both from a computational and qualitative goodness-of-fit-by-eye perspective.

Check out [this comment](https://github.com/LSSTDESC/qp/issues/8#issuecomment-1362271028) in issue #8 for some screenshots of plots and some pseudo code.

**Comment by drewoldag** [comment]
The work in PR #150 should address this issue. The PR does two main things:

1. Reintroduces the original quantile parameterization PDF reconstruction algorithm (taking the analytic derivative of a spline fit to the CDF samples)
2. Allows the user to select between 4 different reconstruction algorithms to use the one that best fits their use case. 

I also created `quantile_parameterization_demo.ipynb` to showcase how the different reconstruction algorithms perform on different types of distributions (single gaussian, rayleigh (non-symmetric), merged gaussians, well separated gaussians (like this ticket)). 

There is still some follow up work to be done and is recorded in issue #148 .

**Comment by drewoldag** [comment]
@sschmidt23 Can we go ahead and close this ticket out after the work that was mentioned above (i.e. PR #150) or do you think we need to keep this open?

**Comment by sschmidt23** [comment]
I think your changes have addressed this and we can go ahead and close, so I'll do that now.
