### ISSUE TITLE
astropy dependence question

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/qp#71]
Hi @eacharles!  I see there was work on this package to remove the [astropy dependence](https://github.com/LSSTDESC/qp/pull/62) back in September.  The requirements.txt file was updated, but [setup.py still seems to require astropy](https://github.com/LSSTDESC/qp/blob/00ce24c749ca1ae1adfa124c31642ba5f6c36a12/setup.py#L24) - is that intended or just an oversight?

I'm trying to install RAIL and qp into a recent LSST Sci Pipelines environment and running into trouble due to the requirement for astropy< 5.

**Comment by eacharles** [comment]
Probably just an oversight.

-e

**Comment by heather999** [comment]
Is it ok for me to create a PR to fix that?

**Comment by eacharles** [comment]
Yes.  And it is also ok for you to approve your own PR, if you are feeling autocratic today.

**Comment by heather999** [comment]
Just one more question  - GitHub suggests that we're one commit behind the aimalz:master repo and wants me to fetch upstream.  Looking at aimalz:master, I don't seen any recent commits so I figure perhaps we're ignoring that commit on aimalz:master (which I think is just that update to the citation)?  Don't want to mussy up things..

**Comment by eacharles** [comment]
Ignore aimalz:master, it is badly out of date.

If you know how to tell that to GitHub, I’m all ears.
-e

**Comment by heather999** [comment]
ah ok - if you want to completely eliminate the fork and disconnect from aimalz:master you can either:
* It looks like GitHub can help us with this if we open a ticket: https://support.github.com/request/fork?tags=fork
OR
* delete and recreate this repo, but obviously you'll lose history and all that
But I'm encouraged to see there is a way to do this - do you guys want to ask GitHub to "detach the fork"?

**Comment by heather999** [comment]
Dealt with in #73
