### ISSUE TITLE
scipy v1.8 compatibility issues

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#72]
After merging in the Delight PR in RAIL, several tests are now failing GH Actions for python3.8.  This appears to be because the earlier install of openMPI and Delight has it grabbing scipy v1.8 rather than v1.7.3 used in previous tests, and we now have several errors like 
`ValueError: operands could not be broadcast together with shapes (399,301) (120099,)`
from `/scipy/stats/_distn_infrastructure.py:453: in pdf`

Cases that seem to be affected: mixmod_gen and interp_gen, but all three of which point to distn_infrastructure's `pdf` and the shapes as quoted above.

**Comment by eacharles** [comment]
Done in #88 and others.
