### ISSUE TITLE
Request mods to setup.py

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/qp#75]
Making two suggestions and open to discussion.. 
* I think it might be clearer to use `scikit-learn` rather than `sklearn` in the requirements (and setup.py).  I think the official package name is scikit-learn and in conda-forge, that's the name that is available, not `sklearn`.
* the  "setuptools_scm", "setuptools_scm_git_archive" only needs to be in the `setup_requires` section of setup.py

This comes up when I conda install the latest `qp` release and then go to pip install something else into that same environment.. pip complains that:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qp 0.5 requires setuptools-scm-git-archive, which is not installed.
qp 0.5 requires sklearn, which is not installed.
```

I think both would be avoided if setup.py were updated... but haven't tested that yet.

**Comment by eacharles** [comment]
Done in #78
