### ISSUE TITLE
Moving native plotting to descqa(?)

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#79]
The native plotting has some platform-specific dependencies that are breaking the demos. Even if per-galaxy visualizations have been lovely for the tutorials, it also hasn't been appropriate in a real use case (e.g. CL nor TD). Can we move this to [descqa](https://github.com/LSSTDESC/descqa)?

**Comment by sschmidt23** [comment]
I actually find a lot of utility in the plot_native functions in qp, so before we do a drastic move to descqa, I'm going to try removing some of the matplotlib setup stuff, dependence on LaTex, and make a couple hardcoded options (e.g. colors for specific types of distributions that forces them all to the same color, non-ideal if plotting multiple PDFs on a single set of axes).  We can then re-evaluate what still needs to change to ensure that people can actually use the plotting functionality.

**Comment by eacharles** [comment]
FWIW, I don't really understand what you are asking for.  I.e., where in desc QA would they live, how would we implement it, how would we access if from qp, etc...  

If we can clarify those issues it might help make it clear what the right option is.

**Comment by aimalz** [comment]
This was discussed a bunch in the SRV WG, somewhat more than a month ago, but DESCQA actually includes a lot of functionality for making diagnostic plots (@yymao can best point you to the relevant code/demo), and the plan is for that to be the interface people use for diagnostics of all DESC catalog data, including the photo-z PDFs. What I'm proposing is that it wouldn't be included in qp at all, eliminating what is currently the sole installation/dependency issue in qp itself. On the other hand, if Sam is really using the native plotting, then it has at least one user, so that's an argument for leaving it where it is. However, if it has exactly one user, then it's probably not worth putting much time/effort into enhancing the native plotting functionality, especially if those improvements would be made by adding it to DESCQA regardless.

**Comment by sschmidt23** [comment]
What exactly is the dependency that fails?  There was one line of LaTex in one of the axis labels that I removed, is there some other dependency that is causing problems?

**Comment by eacharles** [comment]
I’m not understanding what you have in mind instead.   

Sure desc qa can make plots.   But my understanding is that it is a set of tools to help you make a specific set of plots given specific data input, and taking care of the bookkeeping, etc.     I don’t see how that is the same as having a function to draw a pdf in a particular way based on knowing what the underlying representation is.  
It might help if we think about how someone would use desc qa in a notebook to make a plot for a new type of distribution.  I suspect what we will find is that is way more complicated that what we have now, but I might be wrong. 

-e
