### ISSUE TITLE
qp.read does not ingest ancillary data on read in of ensemble file

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#81]
It looks like `qp.read` does not copy the ancillary data when reading an ensemble from file, e.g. if you had
```
ens.set_ancil(extra_stuff_dict)
ens.write_to("testens.pq")
```
it writes things out properly, but if you then do a 
```
newens = qp.read("testens.pq")
```
then the newens.ancil is set to `None` as the ancillary data was not copied.

**Comment by eacharles** [comment]
Fixed with #82
