### ISSUE TITLE
make an autoencoder representation

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#85]
@villrv the version of qp under active development is actually here. I can't directly transfer your issue, aimalz/qp#98, from a repo under my personal account to a repo in an organization so am making a new one here as a reminder for us to follow up with you for details and add it in soon.

**Comment by eacharles** [comment]
I have no idea what this means, could you clarify please?

**Comment by villrv** [comment]
Yes!! Sorry this was from a conference, in which I was sitting next to Alex - ha! This is a recommendation (please correct me if I'm wrong, Alex!) that the p(z) distributions could be described by low-dimensional vectors, which you would learn via an autoencoder (a type of neural network). So the idea would basically be that some p(z) distribution has ~100 bytes of info, and an autoencoder learns a ~10 byte representation of this, which captures the full distribution.

**Comment by eacharles** [comment]
So, basically you are saying we run a really fancy version of gzip on the pdf representation?

**Comment by aimalz** [comment]
@villrv This issue got closed in some spring cleaning as being too general to be actionable, but if you have a piece of code implementing this parameterization, please leave a comment with it and we can reopen the issue for wrapping that.
