### ISSUE TITLE
Risk-based point estimate

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/qp#91]
After the 12 May telecon, it occurred to me that there's at least one other point estimate derived from PDFs (see Sec. 4.2 of [Tanaka+18](https://academic.oup.com/pasj/article/70/SP1/S9/4494086)) that would be nice to have alongside the mean (accessible via `moment`), median (accessible via `ppf`), and mode (actually, is that directly accessible through qp rather than `argmax`ing the `objdata` on grid evaluations?).

**Comment by maxwest-uw** [comment]
Closed with #116
