### ISSUE TITLE
Ensemble mean method looks to return identical values with scipy 1.8.0

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/qp#95]
While testing the update to the Ensemble mode() method on an ensemble with N PDFs, running ens.mean() was returning N identical values (I think with the mean of the first PDF copied N times).  It looks like this is due to scipy 1.8.0 array broadcasting, as trying on my other machine that still had scipy v1.7.1 the mean function properly calculated all N mean values, but then updating to scipy v1.8.0 I once again get the N identical values returned by mean().

**Comment by eacharles** [comment]
And here past Eric thought he was so clever for inheriting the structure from scipy.stats.   Thanks Sam.

**Comment by sschmidt23** [comment]
closed by #94, thanks Eric
